# Generated by Django 4.0.6 on 2022-07-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingModel',
            new_name='ShippingAddress',
        ),
    ]
